CONFIG_MAIN_STACK_SIZE=16384
CONFIG_LV_Z_MEMORY_POOL_CUSTOM_SECTION=y
CONFIG_LOG=y
CONFIG_SHELL=y

CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=8388608
CONFIG_LV_Z_SHELL=y
CONFIG_LV_USE_MONKEY=y

CONFIG_DISPLAY=y
CONFIG_INPUT=y

CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_18=y
CONFIG_LV_FONT_MONTSERRAT_24=y

# Benchmark Demo
CONFIG_LV_USE_FONT_COMPRESSED=y

CONFIG_NEWLIB_LIBC=y
#CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=8192

CONFIG_GPIO=y
CONFIG_GPIO_AMEBA=y
CONFIG_GPIO_DEBOUNCE_EN=y
CONFIG_AMEBA_PPE=y
CONFIG_AMEBA_PPE_INIT_PRIORITY=50

CONFIG_AMEBA_MJPEG=y
CONFIG_AMEBA_MJPEG_INIT_PRIORITY=50

CONFIG_LV_Z_DEMO_BENCHMARK=y
CONFIG_LV_Z_VDB_SIZE=100
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_Z_FLUSH_THREAD=y
CONFIG_LV_Z_DOUBLE_VDB=y
CONFIG_LV_Z_VDB_CUSTOM_SECTION=y
CONFIG_LV_DEF_REFR_PERIOD=16
CONFIG_LV_USE_DRAW_PPE=y
CONFIG_LV_Z_FLUSH_THREAD_STACK_SIZE=8192
CONFIG_LV_Z_FLUSH_THREAD_PRIORITY=5
#CONFIG_LV_Z_MEM_POOL_HEAP_LIB_C=y
CONFIG_LV_Z_DIRECT_MODE=y
CONFIG_LV_IMAGE_HEADER_CACHE_DEF_CNT=3

#CONFIG_PSRAM_HEAP_STD=y

#CONFIG_FLASH_BASE_ADDRESS=0x60000020

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

CONFIG_HEAP_MEM_POOL_SIZE=204800
CONFIG_PSRAM_HEAP_SHARED_MULTI=y
CONFIG_AMEBA_PSRAM_HEAP_SIZE=2097152


CONFIG_LV_USE_LOG=y
#CONFIG_LV_LOG_LEVEL_WARN=y
#CONFIG_LV_LOG_LEVEL=2
#CONFIG_LV_LOG_TRACE_MEM=y
